version: "3.7"
networks:
  hdt1996_network: 
    driver: bridge
services:
  web:
    user: root
    container_name: wscontainer
    networks:
      - hdt1996_network
    build:
      context: .
    volumes:
      - .:/webserver
      - static_data:/vol/web/static
    environment:
      - DEBUG=0
    depends_on:
      - db
  db:
    container_name: dbcontainer
    networks:
      - hdt1996_network

    image: timescale/timescaledb:latest-pg14
    ports:
      - 6432:5432
    volumes:
      - db_vol:/var/lib/postgresql/data
    environment:
      
      POSTGRES_DB: storedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  proxy:
    user: root
    container_name: proxycontainer
    networks:
      - hdt1996_network
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
    ports:
      - 8001:8001
      - 443:443
      - 80:80
    volumes:
      - ./proxy:/etc/nginx/
      - static_data:/vol/static
      - ./media:/vol/media
      - ./frontend/build:/vol/react
    depends_on:
      - web
  ddns:
    container_name: cfcontainer
    image: oznu/cloudflare-ddns:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      - API_KEY=Wec2xia8uiDtrXG3UGo15CYGaEu5651G_9wMCM8A
      - ZONE=192.168.1.17
      - PROXIED=false

volumes:
  db_vol: 
  static_data:


